chore: refactoring build jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,29 +4,97 @@
 name: CI
 
 on:
+  workflow_dispatch: null
+
   push:
     branches:
-      - '**'
+      - main
+
   pull_request:
     branches:
-      - '**'
+      - main
+
+env:
+  GO_VERSION: 1.21
 
 jobs:
-  lint:
+  Analyze:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - uses: actions/setup-go@v3
-        with:
-          go-version: '1.21'
-      - uses: golangci/golangci-lint-action@v3
 
-  test:
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: ${{ env.GO_VERSION }}
+
+      - name: Install Dependencies
+        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
+
+      - name: Lint
+        run: golangci-lint run ./...
+
+  Test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - uses: actions/setup-go@v3
-        with:
-          go-version: '1.21'
-      - run: go test -v ./...
 
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: ${{ env.GO_VERSION }}
+
+      - name: Install Dependencies
+        run: |
+          go install github.com/golang/mock/mockgen@latest
+          go install github.com/jstemmer/go-junit-report@latest
+          go install github.com/onsi/ginkgo/v2/ginkgo
+
+      - name: Generate Mocks
+        run: go generate ./...
+
+      - name: Test
+        run: ginkgo --junit-report=junit.xml ./...
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/junit.xml'
+          fail_on_failure: true
+          require_tests: true
+          annotate_notice: false
+          detailed_summary: false
+
+  Build:
+    needs: [analyze, test]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: ${{ env.GO_VERSION }}
+
+      - name: Install Dependencies
+        run: |
+          go mod download
+
+      - name: Build
+        run: make build
+
+  Publish:
+    needs: build
+    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v2
+        with:
+          go-version: ${{ env.GO_VERSION }}
+      - uses: go-semantic-release/action@v1
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
